### ISSUE TITLE
Functional components in metal.js

### ISSUE THREAD

**Issue by AngeloYoun** [metal/metal.js#105]
React has functional components which don't have lifecycle methods. It is not a critical feature but it does help make the code more readable and react is planning to do interesting things in the future with this feature. It might make sense for metal to also have an equivalent.

**Comment by mairatma** [comment]
Thanks a lot for the suggestion, I agree that this would be really good to have. And it shouldn't be hard to do it, so I'll try to work on it soon.

**Comment by mairatma** [comment]
This feature was added through https://github.com/metal/metal-incremental-dom/issues/3. You just need to update your dependencies to use it :)
