### ISSUE TITLE
Metal Lifecycle Method equivalent of componentWillReceiveProps()

### ISSUE THREAD

**Issue by AngeloYoun** [metal/metal.js#106]
We have a case where we want to be listening for a change when a config has been updated to a new value.

In React, the way this was done was through listening for any changes to props and then identifying if the prop being changed is different to the old.

```
componentWillReceiveProps(nextProps) {
    if (JSON.stringify(this.props.foo) !== JSON.stringify(nextProps.foo)) {
        this.changeAction();
    }
}
```

I am not convinced that this is the best way of doing this so any alternatives to including a lifecycle method would also be fine.

Thank you!
Angelo Youn

**Comment by cirocosta** [comment]
I'm not the best to answer this but as [`Component`](https://github.com/metal/metal-component/blob/master/src/Component.js#L54) extends [`State`](https://github.com/metal/metal-state) and from [`State`'s test](https://github.com/metal/metal-state/blob/master/test/State.js#L464)  you can check that you can listen to a change, that's probably the equivalent of what you want . 

that's my 2 cents, @mairatma can certainly provide you a better answer 🙈

**Comment by yuchi** [comment]
The main difference is between _listening to the change of a key_ to a _lifecycle phase between injection of new values and application of those_.

**Comment by yuchi** [comment]
The nearer you can get is by using [`configChanged`](https://github.com/metal/metal-state/blob/50e4f75ec98b3be7e1b4d3c34f80b9bcd08840a7/test/State.js#L698)

**Comment by mairatma** [comment]
Oh yeah, I had forgotten about this event, thanks for mentioning it @yuchhi. Maybe the name is not very intuitive, but it will also be called on the first time that `config` is set. Do you guys think it's worth having the lifecycle version as well, or is this event good enough?

**Comment by AngeloYoun** [comment]
Oh thanks for that, I think that will suite my purpose fine. Thank you!

**Comment by yuchi** [comment]
@AngeloYoun since AFAIK Metal doesn’t differentiate between state (internal attributes) and props (public attributes) you can potentially create an infinite loop by updating the configuration during a `configChanged` event.

**Comment by mairatma** [comment]
I'll close this since the event is covering the desired use case :)

**Comment by natecavanaugh** [comment]
@yuchi I just wanted to comment that the way you described the state/props in React is probably the most coherent and concise way of describing them that I've read online :)

**Comment by yuchi** [comment]
Ahahah thank you @natecavanaugh!
