### ISSUE TITLE
Rendering a metal component appends component to node rather than replacing node

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#110]
When rending a metal component, is there a reason for appending the component to the `parentElement` rather than replacing the node? For our use case, it is usually better to replace the node with our metal component rather than appending it. 

``` js
new MyComponent(
     {},
     parentElement
);
```

Just curious what the thought is behind this. Thanks!

**Comment by eduardolundgren** [comment]
What you want is set the component element to your element:

``` js
new MyComponent(
     {
         element: elementNode
     }
);
```

**Comment by mairatma** [comment]
Oops, closed by mistake.

I just meant to confirm that we have both options, like Eduardo said. @bryceosterhaus, let us know if it covers your use case :)

**Comment by mairatma** [comment]
Hate this `Close and comment` button sometimes...

**Comment by bryceosterhaus** [comment]
Oh gotcha, didn't notice that attr before. Thanks!
