### ISSUE TITLE
SVG support for metal-jsx?

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#113]
Does metal-jsx templating support svgs and their attributes? I am trying to to implement

``` html
<svg>
     <use xlink:href="">
     </use>
</svg>
```

And the `xlink:href` attribute doesn't seem to work.

One way I got around this was creating an attribute object and using an es6 spread

``` js
const xlink = {
    'xlink:href': href
}

<use {...xlink}></use>
```

Should we add additional parsing for metal-jsx so that xlink:href is supported or just side step the issue by using the attribute object?

**Comment by mairatma** [comment]
Thanks for reporting this! It seems to be an issue with the tool we're using to compile from jsx to incremental dom. At least when I try using this `xlink:href` attribute you've mentioned I get a compilation error, so I [reported it there](https://github.com/jridgewell/babel-plugin-incremental-dom/issues/54) to see if we can get a fix.

**Comment by mairatma** [comment]
This has been fixed on babel-plugin-incremental-dom, and I've updated our [preset](https://www.npmjs.com/package/babel-preset-metal-jsx) to enable its usage.

Just make sure that you use version 0.0.3 or higher of babel-preset-metal-jsx (or if you're not using the preset, make sure that babel-plugin-incremental-dom is 3.3.0 or higher and sets `namespaceAttributes` to true).

**Comment by bryceosterhaus** [comment]
Thank you!
