### ISSUE TITLE
Error building "1. Hello World" example

### ISSUE THREAD

**Issue by ipeychev** [metal/metal.js#114]
Hello,

Executing `npm run build` command in "1. Hello World" example does not finish successfully.

Steps to reproduce:
1. Download [boilerplate-jsx](http://metaljs.com/downloads/boilerplate-jsx.zip)
2. Unzip, then go to `boilerpate-jsx/1. Hello World`
3. Execute `npm i`, then `npm run build`. The result is:

``` bash
➜  1. Hello World pwd
/Users/iliyan/Downloads/boilerpate-jsx/1. Hello World
➜  1. Hello World npm i
npm WARN karma-chai@0.1.0 requires a peer of karma@>=0.10.9 but none was installed.
npm WARN karma-commonjs@0.0.13 requires a peer of karma@>=0.9 but none was installed.
npm WARN karma-sinon@1.0.5 requires a peer of karma@>=0.10 but none was installed.
npm WARN metal-modal@0.0.0 license should be a valid SPDX license expression
➜  1. Hello World npm run build

> metal-modal@0.0.0 build /Users/iliyan/Downloads/boilerpate-jsx/1. Hello World
> gulp build

[22:27:37] Using gulpfile ~/Downloads/boilerpate-jsx/1. Hello World/gulpfile.js
[22:27:37] Starting 'build'...
[22:27:37] Starting 'clean'...
[22:27:37] Finished 'clean' after 12 ms
[22:27:37] Starting 'css'...
[22:27:37] Starting 'soy'...
[22:27:37] Finished 'soy' after 24 ms
[22:27:37] Starting 'build:js'...
[22:27:37] Starting 'build:globals:js'...
Error in plugin 'metal'
Message:
    document is not defined
[22:27:38] Finished 'build:globals:js' after 312 ms
[22:27:38] Finished 'build:js' after 312 ms
[22:27:38] Finished 'css' after 361 ms
[22:27:38] Starting 'uglify'...
[22:27:38] Finished 'uglify' after 3.75 ms
[22:27:38] Finished 'build' after 380 ms
➜  1. Hello World
```

Expected result:
The required artifacts for running the demo page to be created successfully.

Actual result:
There were no any artifacts created.

Used OS:
MacBook Pro, v10.10.5

Node version:
v5.6.0

NPM version:
3.6.0

Thanks,

**Comment by eduardolundgren** [comment]
I've got the same issue here.

**Comment by eduardolundgren** [comment]
It only happens on `boilerplate-jsx` the `soy` one is fine. Will investigate what's going on.

**Comment by mairatma** [comment]
Weird, I'm taking a look

**Comment by mairatma** [comment]
Thanks for reporting this @ipeychev :D

I've fixed this and made sure that all the examples are working now.

**Comment by ipeychev** [comment]
Great 👍

**Comment by ipeychev** [comment]
One more note - in the site it is written:
"If you want you can also turn header and bodyinto state properties. That way when you type something like modal.header = 'New Header', the contents will also be updated automatically."

The user will try to do something as on the following screencast and he/she will wonder what is he/she doing wrong, because the header is not being updated. It would be good to show such an example.
![bug](https://cloud.githubusercontent.com/assets/78014/15549757/647cf5e8-22ae-11e6-8ba8-28ade54a4cc9.gif)

**Comment by mairatma** [comment]
You're right, it's not clear from the text that there's an extra step converting the `this.config.header` and `this.config.body` calls to `this.header` and `this.body`. I've created a separate issue to track this: https://github.com/metal/metaljs.com/issues/23.
