### ISSUE TITLE
Returning an array with an empty string in JSX results in js error

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#117]
If an array every contains an empty string, results in js error.

`Uncaught TypeError: Cannot read property 'key' of undefined`

``` js
render() {
    return (
        <div>
            {['foo', '', ' bar']}
        </div>
    );
}
```

**Comment by mairatma** [comment]
Hmm interesting, I'll take a look and see if it's a problem on our side or on the compiler's.

**Comment by mairatma** [comment]
Fixed [here](https://github.com/metal/metal-incremental-dom/issues/12) :)
