### ISSUE TITLE
Render children without a wrapping element

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#122]
Trying to replicate a similar component to https://github.com/facebook/react/blob/master/src/addons/transitions/ReactCSSTransitionGroupChild.js#L167

I would expect this to work like...

``` jsx
class Parent extends JSXComponent {
    rendered() {
        this.element.className = 'test';
    }

    render() {
        return this.children[0];
    }
}

class Child extends JSXComponent {
    render() {
        return (
            <div>
                I'm a child!
            </div>
        );
    }
}


// Implementation

<Parent>
    <Child />
</Parent>


// Expected Markup Result

<div class="test">
    I'm a child!
</div>
```

Is this possible? Or are there reasons why we shouldn't have this be possible?

**Comment by mthadley** [comment]
@bryceosterhaus I think it might already work this way: https://github.com/metal/metal-jsx/commit/cea04a8a9d27a4eef066d4843cd549332df21035#diff-60cffaf471498fafe64649ed28d9abb3R163

**Comment by bryceosterhaus** [comment]
You're totally right, I didn't see that update. Thanks!
