### ISSUE TITLE
FYI: Moving to github.com/metal/metal

### ISSUE THREAD

**Issue by mairatma** [metal/metal.js#132]
I'm just creating this issue as a kind of announcement that we've moved from this repository to [metal/metal](https://github.com/metal/metal) now.

It's not a straightforward move, otherwise you wouldn't even notice it. We've actually merged the core Metal.js repos into a single place that will track them together (using [lerna](https://lernajs.io/), like babel does). This has lots of advantages, one of which being that now we'll have a single place for reporting issues. Issues were generally being reported here, but they were fixed in other repos spread within the organization, which made it confusing to track them.

This won't change how each library is used though. We'll keep publishing them separately in npm as before, the only difference is that their code is in the same place.

**Comment by yuchi** [comment]
Awesome!

**Comment by mairatma** [comment]
So, as I explained in more details [in this other issue](https://github.com/mairatma/metal-lerna/issues/16), we've moved back here (still using lerna and grouping all packages though, so nothing changes in practice).

Closing this issue, since it's not valid anymore :)
