### ISSUE TITLE
Use gh-pages for `demos` for metal-* components

### ISSUE THREAD

**Issue by mairatma** [metal/metal.js#133]
_From @cirocosta on July 19, 2016 18:20_

Hey!

I've noticed that most of the `metal-*` repositories have a `demo(s)` directory, but they are just "runnable" if `git cloning` and then running the build steps. It'd be pretty cool to have them just one click away by using `gh-pages` to provide that. What do you think about setting a script for publishing them? There are various examples about travis integration that pushes to `gh-pages` when a push to master is done. 

Thx! 👯 

_Copied from original issue: mairatma/metal-lerna#15_

**Comment by mairatma** [comment]
The plan so far was to have Metal.js's site include the demos, but we haven't managed to start working on that yet.

Your idea is very good though, and could be done even before the website is ready to include demos. We don't have travis set up for each repo yet either, but we could have a gulp task until that's ready, like we do for metaljs.com. What do you think @eduardolundgren and @zenorocha?

**Comment by mairatma** [comment]
_From @zenorocha on July 19, 2016 20:51_

Yeah, we just need to make sure that these demos are going to be up to date.

**Comment by jbalsas** [comment]
@blzaugg, @zenorocha, can you guys go over this as part of the `metaljs.com` update?

**Comment by blzaugg** [comment]
@Robert-Frampton, can/should we automated this into Electric? Or is this too specific to Metaljs.com?

**Comment by robframpton** [comment]
Sounds too specific to metaljs.com's use case.

**Comment by blzaugg** [comment]
K. I'll talk to @zenorocha.
