### ISSUE TITLE
Event delegation should skip "disabled" elements

### ISSUE THREAD

**Issue by mairatma** [metal/metal.js#134]
_From @mairatma on July 5, 2016 17:37_

Events don't trigger for disabled elements natively, even when bubbling. Our event delegation doesn't respect that though, since it catches the event in the component's element and doesn't check for disabled states.

Need to investigate which elements are automatically skipped natively (button for sure, but maybe more of them too).

_Copied from original issue:_ https://github.com/metal/metal-events/issues/2

_Copied from original issue: mairatma/metal-lerna#2_

**Comment by mairatma** [comment]
_From @fernandosouza on July 16, 2016 18:53_

👍

**Comment by mairatma** [comment]
_From @fernandosouza on July 17, 2016 22:45_

Hi, @mairatma. I'm taking care of this issue now. I'll send you any feedback as soon as I can.

**Comment by mairatma** [comment]
_From @fernandosouza on July 18, 2016 2:44_

@mairatma. I've followed the steps in the README.md but I've got this error after running the "npm test" command.

I don't think it's related to the Metal, but could you give me a hand?

> @ pretest /Users/fernandosouza/Projects/metal/source-code
> npm run compile
> 
> @ compile /Users/fernandosouza/Projects/metal/source-code
> lerna run compile

Too many arguments.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ compile: `lerna run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ compile script 'lerna run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fernandosouza/Projects/metal/source-code/npm-debug.log
npm ERR! Test failed.  See above for more details.

**Comment by mairatma** [comment]
Weird, is this the full log? Seems like it's no really saying where the problem is, so it's hard to figure it out. Can you run again and make sure to output the whole thing, from your command (which doesn't show up here, but I assume is `npm test` to the end of the error?

**Comment by mairatma** [comment]
_From @yuchi on July 18, 2016 15:8_

I believe it’s there, just badly formatted:

```
> @ pretest /Users/fernandosouza/Projects/metal/source-code
> npm run compile

> @ compile /Users/fernandosouza/Projects/metal/source-code
> lerna run compile

Too many arguments.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v5.11.1
npm ERR! npm v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ compile: lerna run compile
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ compile script 'lerna run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! lerna run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/fernandosouza/Projects/metal/source-code/npm-debug.log
npm ERR! Test failed. See above for more details.
```

**Comment by mairatma** [comment]
_From @mthadley on July 18, 2016 16:58_

I also tried to run the tests right after the mono-repo was created, but I saw the same error. It seemed strange since I couldn't find any docs on the `run` command for `lerna`.

**Comment by mairatma** [comment]
hmmm weird, I'm going to try to reproduce by recreating this now

**Comment by mairatma** [comment]
Oh, actually I think I know what it is. My `README.md` instructions are wrong, it tells you to install lerna via `npm -g i lerna` but that will install version 1.x, while we're using 2.x already (they recommend using 2.x for new projects, but leave latest as 1.x).

So you need to install lerna via `npm install -g lerna@^2.0.0-beta` instead. That's probably why the command isn't working.

**Comment by mairatma** [comment]
Fixed the instructions here: https://github.com/metal/metal/commit/619c71cd838f6382fa74f111376d05a62c1bffee

**Comment by mairatma** [comment]
_From @fernandosouza on July 18, 2016 17:28_

Now it's working. Thanks @mairatma.

Some commands I have to use `sudo` but it's working.

**Comment by mairatma** [comment]
Yeah, I usually need `sudo` for installing global dependencies, but it shouldn't be necessary for other things. Did you need it with any lerna command or sth like that?

**Comment by mairatma** [comment]
_From @fernandosouza on July 18, 2016 18:34_

Yeah. I've needed it to `sudo lerna bootstrap` and `sudo npm test` (maybe for `lerna run compile` command) and also to install lerna.

**Comment by mairatma** [comment]
Fixed by https://github.com/metal/metal.js/commit/d2293a19bb3c02d87f4ea19cef3834e9c3a2b5a6.

**Comment by fernandosouza** [comment]
@mairatma. I think I found the problem that Chema mentioned. Maybe we should reopen this issue and I will send you a new PR.

**Comment by mairatma** [comment]
This has now been fixed in master :D
