### ISSUE TITLE
Validators no longer print the name of their component.

### ISSUE THREAD

**Issue by mthadley** [metal/metal.js#141]
I'm seeing errors like this:

``` console
Warning: Error: Warning: Invalid state passed to 'onClick'. Expected type 'function', but received type 'undefined'. Passed to 'State'.
```

I'm guessing that the `State` in these cases is an instance of `metal-state`.

**Comment by mairatma** [comment]
Hmmm that makes sense, since `State` is not the actual component anymore. That's a good catch, I'll fix this!
