### ISSUE TITLE
Suggestion. Could we have a keyCode map?

### ISSUE THREAD

**Issue by fernandosouza** [metal/metal.js#168]
In order to work easily with keyboard events, it will be nice to have a keyCode map like http://yuilibrary.com/yui/docs/event/key.html

**Comment by yuchi** [comment]
You can steal this as a starting point: https://github.com/smclab/react-faceted-token-input/blob/master/src/key-codes.js

Of course you'd also need the reversed map (`code -> key`).

**Comment by fernandosouza** [comment]
Cool, @yuchi! Thank you! :)

**Comment by yuchi** [comment]
You can access them as a single object with `import * as codes from …`.

**Comment by fernandosouza** [comment]
I began to implement.

**Comment by mairatma** [comment]
Just FYI, Fernando added this as a separate module called [metal-key](https://github.com/metal/metal-key).
