### ISSUE TITLE
Try saucelabs in travis with encrypted access key again

### ISSUE THREAD

**Issue by mairatma** [metal/metal.js#172]
Travis didn't allow usage of encrypted environment variables when running tests for pull requests from forks. Due to that we're currently using a less safe way of passing our access key to saucelabs.

It seems like they've [recently fixed](https://github.com/travis-ci/travis-ci/issues/1946#issuecomment-253590174) this use case though, as long as you use the jwt addon for the encrypted var, so we should try it out.

**Comment by fernandosouza** [comment]
I'm working on it.

**Comment by fernandosouza** [comment]
I've already created an issue on Gulp Metal required for this one.
https://github.com/metal/gulp-metal/issues/35
