### ISSUE TITLE
Add Metal.js to list of incremental dom known libraries

### ISSUE THREAD

**Issue by mairatma** [metal/metal.js#173]
We should add Metal.js to incremetal dom's [page](https://github.com/google/incremental-dom/blob/master/ECOSYSTEM.md#libraries) of known libraries. We can probably do this via a pull request to them.

**Comment by fernandosouza** [comment]
Just updating this issue. @brunobasto has already sent a Pull including it.
https://github.com/google/incremental-dom/pull/313

**Comment by pragmaticivan** [comment]
https://github.com/google/incremental-dom/pull/313 is already merged.

Thanks!
