### ISSUE TITLE
Adds Node.js support

### ISSUE THREAD

**Issue by eduardolundgren** [metal/metal.js#188]
Adds ability to use Metal.js in Node.js to allow features such as server side rendering for JSX and Soy components.

**Comment by eduardolundgren** [comment]
@mairatma When you have time, could you take a look on those changes and give your opinion? All tests are passing for Node.js (note that metal-bundle-soy `node` branch is required).

https://github.com/metal/metal.js/tree/node

**Comment by mairatma** [comment]
Sure, I took a look and it lgtm :)
