### ISSUE TITLE
hasClassWithNative_ throws an error when trying to check for several classes

### ISSUE THREAD

**Issue by antoniopol06** [metal/metal.js#209]
The [`hasClass`](https://github.com/metal/metal.js/blob/master/packages/metal-dom/src/domNamed.js#L327)  method throws an error if it is invoked with a list of several classes when `classList` is available, for example:

```javascript

import {dom} from 'metal-dom';

let el = document.createElement('div');
el.classList.add('foo');
el.classList.add('bar');

dom.hasClass(el, 'foo bar'); // throws 
```

But, if `classList` is not available it works without errors.

**Comment by fernandosouza** [comment]
Hello, @antoniopol06. Can you share the error message?

**Comment by fernandosouza** [comment]
It's probably the token native error message alerting that the white space is not allowed. `Uncaught DOMException: Failed to execute 'contains' on 'DOMTokenList': The token provided ('foo bar') contains HTML space characters, which are not valid in tokens.`

We try to follow the DOM native API but our implementation of `hasClass` method is producing 2 different behaviours. We are going to look into it. Thank you.

**Comment by eduardolundgren** [comment]
The hasClass only accepts one class per time, this matches the native behavior of classList contains.

**Comment by fernandosouza** [comment]
Hey, @eduardolundgren. `hasClass` follow the native behaviour. But the method also has a fallback for browsers that don't have support for `classList` ([hasClassWithoutNative_](https://github.com/metal/metal.js/blob/master/packages/metal-dom/src/domNamed.js#L353)), and this method uses `indexOf()` to find the given class name inside `element.className`. In this case, you can pass multiple class names separated by space.

This is what @antoniopol06 has reported.

In case to follow the same behaviour, the fallback method should also throw an error when it receives more than one class name.

**Comment by eduardolundgren** [comment]
Got it. Yes they should behave the same (as the native one).

**Comment by fernandosouza** [comment]
Correcting what I said before, throws an error seems not be the right approach for this. Once [`tokenList.contains()`](https://dom.spec.whatwg.org/#dom-domtokenlist-contains) specification says: `The contains(token) method, when invoked, must return true if token is in tokens, and false otherwise.`

So, it says nothing about throws an error if white spaces are passed. And throws an error seems to be a Chrome implementation only.

In this case, we should return false if white spaces are passed.

**Comment by jbalsas** [comment]
Fixed in https://github.com/metal/metal.js/pull/231!
