### ISSUE TITLE
Update the custom mouse events handler to use Metal contains() implementation

### ISSUE THREAD

**Issue by fernandosouza** [metal/metal.js#212]
In a nutshell, we have to update [this line](https://github.com/metal/metal.js/blob/eb2ed3330deda05fff8ffb50ac696e7406259cb5/packages/metal-dom/src/events.js#L18) to use [this method](https://github.com/metal/metal.js/blob/master/packages/metal-dom/src/domNamed.js#L205)

**Comment by fernandosouza** [comment]
cc. @eduardolundgren

**Comment by brunobasto** [comment]
Hey @fernandosouza, is that to provide support for IE9?

**Comment by fernandosouza** [comment]
It's for that too, @brunobasto. Once we have an implementation with a fallback in `metal-dom` module I think it's better we use it. Doing that we will make sure that any additional update will be used. 😃

**Comment by brunobasto** [comment]
Sure. Was just trying to understand what issues you might be experiencing. Thx

**Comment by eduardolundgren** [comment]
@fernandosouza yes, that's correct
