### ISSUE TITLE
<!DOCTYPE html> can not be parsed by soy

### ISSUE THREAD

**Issue by peterborkuti** [metal/metal.js#219]
Hi,

I'd like to create soy templates like
```
{namespace IFrameDoctype}


/**
 *
 */
{template .render}
    <!DOCTYPE html>
    <html>
      <head>
      </head>
      <body>
      </body>
    </html>
{/template}

```
However, HTMLParser could not parse <!DOCTYPE>.
I started to fixing HTMLParser, however I have read, that this is not an html tag (https://www.w3schools.com/tags/tag_doctype.asp) so probably not HTMLParser is responsible for this.

What do you think?
Google's SoyToJsSrcCompiler.jar can create a js from a Soy template which contains ```<!DOCTYPE html>```.

Thank you in advance
Péter

**Comment by fernandosouza** [comment]
Hi, @peterborkuti. Thank you for reporting this. In order to help us understanding the problem, could you share the error message?

**Comment by peterborkuti** [comment]
Hi @fernandosouza,

Sorry for reporting this, now I could not reproduce the issue.
