### ISSUE TITLE
Listener attributes not rendered properly

### ISSUE THREAD

**Issue by jbalsas** [metal/metal.js#222]
Currently, incremental-dom renderer is outputing something like:

```html
<div class="alert alert-dismissible alert-success fade" role="alert">
  body
  <button type="button" class="close" aria-label="Close" data-onclick="data-onclick">
    <span aria-hidden="true">×</span>
  </button>
</div>
```

where it should be rendering

```html
<div class="alert alert-dismissible alert-success fade" role="alert">
  body
  <button type="button" class="close" aria-label="Close" data-onclick="onClickHandler_">
    <span aria-hidden="true">×</span>
  </button>
</div>
```

This is likely caused by https://github.com/metal/metal.js/blob/master/packages/metal-incremental-dom/src/render/attributes.js#L98 where we should do instead `fn.givenAsName_ = value;`

**Comment by jbalsas** [comment]
Hey @fernandosouza, in case you aren't already... could you take a look at this and try to come up with a test and a proper fix?

Thanks!

**Comment by fernandosouza** [comment]
Sure, @jbalsas.
