### ISSUE TITLE
Rename metal-incremental-dom/src/intercept

### ISSUE THREAD

**Issue by yuchi** [metal/metal.js#228]
Ok, I know I’ll sound silly but…

<img width="690" alt="schermata 2017-04-19 alle 11 17 38" src="https://cloud.githubusercontent.com/assets/646609/25172607/d6848462-24f1-11e7-8821-1ad12f3ebd7c.png">

What is going on here is that my ad blocker ([uBlock](https://www.ublock.org/)) is considering `intercept` as a bad keyword.
It is even worse when paired with combo loading: the whole combo is “blocked by client”.

**Comment by robframpton** [comment]
@jbalsas can we look into this? Various people have ran into this very issue, and it's probably worth while since uBlock is a popular tool.

Plus we won't get as many misleading bug reports in Portal :)

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, @yuchi, I've sent https://github.com/metal/metal.js/pull/236 renaming `intercept.js` to `IncrementalDomAop.js`

**Comment by jbalsas** [comment]
This was fixed by https://github.com/metal/metal.js/pull/236/commits/502880a2d444c78da81a9a04dddd429253c07546 and released in `2.11.0`
