### ISSUE TITLE
Nested component tutorial issue

### ISSUE THREAD

**Issue by caneta** [metal/metal.js#238]
I'm following your tutorials, JSX version.
Everything works fine till the [nested component one](http://metaljs.com/docs/modal_nested.html): I copy and paste all the code and when I run it, in the browser console I get the following :
```
Uncaught ReferenceError: CloseHeader is not defined
```
Is there some import missing?

**Comment by mthadley** [comment]
@caneta  Correct, you will need to import `CloseHeader`:
```js
import CloseHeader from './path/to/Closeheader';
```
Alternatively, you could just define `CloseHeader` in the same scope as the `Modal` component.

**Comment by caneta** [comment]
Ok, the file is in the same directory of _Modal.js_ so using the following, it works:
```
import CloseHeader from './Closeheader'
```
It would be great to update the documentation...thank you!
