### ISSUE TITLE
Multiple declarations of "goog.string" with webpack and Soy

### ISSUE THREAD

**Issue by pipiobjo** [metal/metal.js#251]
Hi, 
I evaluating metaljs for our liferay project and we try to build liferay independent metal components. 
And we struggling with placing multiple metal components on one page. 

I get following error: 

`
LoadingAnimator.js:7893 Uncaught Error: Namespace "goog.string" already declared.
    at Object.goog.provide (LoadingAnimator.js:7893)
    at LoadingAnimator.js:9817
    at Object.<anonymous> (LoadingAnimator.js:12259)
    at Object.defineProperty.value (LoadingAnimator.js:12260)
    at __webpack_require__ (LoadingAnimator.js:21)
    at Object._typeof (LoadingAnimator.js:7329)
    at __webpack_require__ (LoadingAnimator.js:21)
    at Object.defineProperty.value (LoadingAnimator.js:62)
    at __webpack_require__ (LoadingAnimator.js:21)
    at Object.defineProperty.value (LoadingAnimator.js:41)
`

I started with the sample project from here https://github.com/metal/metal-examples/tree/master/custom-build/webpack 

* Define a second component 
* Importing them on the index.html and there is the error. 

I provide a sample project for reproduction: 
https://github.com/pipiobjo/metaljs-webpack

I didnt test if this also appears with other build mechanism. 
If you need more information, I will try to help ;-)

**Comment by jbalsas** [comment]
Hey @pipiobjo, both entries in your configuration `Modal` and `LoadingAnimator` are including `IncrementalDOM` in their bundles, which will cause the error you're seeing when loaded in the same page.

You should be able to either extract `IncrementalDOM` as a vendor bundle that can be shared, or build all the app together in just one bundle.

I'll work to provide a working scenario tomorrow morning, but maybe this can get you going.

**Comment by jbalsas** [comment]
Hey @pipiobjo, I've sent you a [simple PR](https://github.com/pipiobjo/metaljs-webpack/pull/1) showing how to use the `commonsChunk` plugin to dedupe the `IncrementalDOM` dependency. Also, you can simply use `metal-tools-soy` to compile the soy files, which should make your build lighter 😉 

Please, let us know if that works for you!

**Comment by brunobasto** [comment]
Hey @pipiobjo, did the solution provided by @jbalsas work?

**Comment by jbalsas** [comment]
Closing as we're using this across projects. Please, @pipiobjo, let us know if this didn't work for you so we can better help you with it!
