### ISSUE TITLE
Improve error message when using `oneOf` validation

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#254]
When using `oneOf` validation for a Component property, I would like the error message to display the valid types.

This is what is currently displayed.

```
Error: Warning: Invalid state passed to 'type'. Expected one of given values. Passed to 'MyComponent'.
```

This is what I'd like to see.

```
Error: Warning: Invalid state passed to 'type'. Expected one of the following values: 'value1', 'value2', 'value3'. Passed to 'MyComponent'.
```

**Comment by robframpton** [comment]
@mthadley @bryceosterhaus, as you guys have used these kind of validators a lot, what do you think?

**Comment by mthadley** [comment]
Sounds like an awesome improvement to me. Since any type can appear in `oneOf`, we should also make sure developers don't end up with something like this in their console:
```
Expected one of the following values: '[object Object]', '[object Object]', '[object Object]'.
```

**Comment by jbalsas** [comment]
This has already been merged into `develop`!
