### ISSUE TITLE
Support for OOTB isomorphic rendering

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#267]
It's currently possible to achieve server side rendering of Metal.js components, but it requires libraries such as https://www.npmjs.com/package/jsdom to accomplish.

```javascript
// Node.js 
const JSDOM = require('jsdom').JSDOM;

const { document } = (new JSDOM()).window;

global.document = document;
global.window = document;

const Component = require('metal-component').Component;

const MyComponent = require('./MyComponent').MyComponent;

const htmlString = Component.renderToString(MyComponent);
```

However, it would be nice to have out of the box isomorphic rendering.

```javascript
// Node.js 
const Component = require('metal-component').Component;

const MyComponent = require('./MyComponent').MyComponent;

const htmlString = Component.renderToString(MyComponent);
```

I have sent the following three pull requests relating to server side rendering of components.

https://github.com/metal/metal.js/pull/264 (metal-dom)
https://github.com/metal/metal.js/pull/265 (metal-soy)
https://github.com/metal/metal.js/pull/266 (metal-incremental-dom)

With these changes the second code snippet above should work correctly in a Node.js environment. Once/if these branches are merged, I would like to create a server side integration test separate from the current testing environment we have set up for this repo to test this functionality.

Update: I've sent another PR that adds a simple test for server side rendering.

https://github.com/metal/metal.js/pull/269

**Comment by brunobasto** [comment]
Awesome, Rob!

**Comment by jbalsas** [comment]
Nice!!

@Robert-Frampton, following the example of the WebComponents story, could we prepare a guide on top of https://github.com/Robert-Frampton/metaljs.com/commits/tutorials?

**Comment by robframpton** [comment]
Hey @jbalsas 

I sent a separate PR https://github.com/metal/metaljs.com/pull/70.

**Comment by jbalsas** [comment]
All pieces have been merged into `develop`!
