### ISSUE TITLE
Automate creation of CustomElements

### ISSUE THREAD

**Issue by jbalsas** [metal/metal.js#268]
We should have a simple way to create and register `CustomElements` out of metal components.

This should include:

- [x] Implementation (https://github.com/metal/metal.js/pull/261)
- [x] Tests (https://github.com/metal/metal.js/pull/261)
- [x] Documentation (https://github.com/Robert-Frampton/metaljs.com/commit/a5fc04952a3aae321c1ef0cdc3e8a2225d663ef0)

**Comment by robframpton** [comment]
Hey @jbalsas 

Do the tests written in #261 satisfy the `Tests` checkbox above? Or did you have something else in mind?

**Comment by jbalsas** [comment]
Sure they do, @Robert-Frampton!!

**Comment by jbalsas** [comment]
This has been merged into `develop`
