### ISSUE TITLE
metal-soy-bundle shouldn't be so fragile

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#273]
In working on creating a lerna repo with multiple soy components in `packages`, I ran into the familiar error `Uncaught Error: Namespace "goog.string" already declared.`.

In most scenarios we're already deduping our bundles which is fine, but it shouldn't be a requirement for simply importing more than one Soy component into a bundle, and it's not actually easy to perfectly dedupe in some testing environments. We should continue to dedupe, and encourage others to do the same, but `metal-soy-bundle` shouldn't be so fragile.

If it's a file that can truly only be loaded once in the client, then why not set some kind of flag to indicate that the bundle has been loaded already? Then check that flag before trying to invoke it a second time?

[Here](https://github.com/metal/metal.js/blob/master/packages/metal-soy-bundle/gulpfile.js#L26) we are already prepending some logic to the file, if we add a simple snippet it should prevent those errors from being thrown.

```javascript
if (this.__METAL_SOY_BUNDLE_LOADED__) {
  return;
}
this.__METAL_SOY_BUNDLE_LOADED__ = true;
```

We could even show a warning that the file has been imported multiple times, so that we're still encouraging deduping.

I suppose we could also check to see if `goog.string` is defined, I guess I just like the idea of being more explicit so the intention of the check is more obvious.

@jbalsas @brunobasto 

Edit: [just so it's more clear](https://github.com/Robert-Frampton/metal.js/commit/eeb36e083db5e1a499c270560d108b3b6a5f6ccc)

**Comment by jbalsas** [comment]
Sounds good to me!

**Comment by jbalsas** [comment]
Merged into `develop`! 🎉

**Comment by jbalsas** [comment]
We reverted this, so I'm reopening and removing the `2.14.0` milestone for now until we rethink this approach.

@yuchi, feel free to voice your concerns here!

**Comment by yuchi** [comment]
I do understand the libraries used behind the scenes are leaky, but Metal should work well even when different versions of it are loaded in the same page (as I said in the other issue).

I’ll have a look at the sources as soon as I can (that means in a while…).
