### ISSUE TITLE
Improve error message on validators

### ISSUE THREAD

**Issue by diegonvs** [metal/metal.js#279]
After @Robert-Frampton changes of oneOf on #272 i was reviewing some test cases on clay-components and i’ve saw that `shapeOf` and `arrayOf` error messages keeps returning simple messages like:
>  Warning: Error: Warning: Invalid state passed to 'icon'. `Expected object with a specific shape.` Passed to 'ClayButton’.

I suggest enhance some text messages on validators to user get the attr with problem more faster.

What do you think, folks?

**Comment by robframpton** [comment]
We can definitely look into improving those error messages as well.

**Comment by diegonvs** [comment]
#297

**Comment by robframpton** [comment]
Fixed by https://github.com/metal/metal.js/pull/315
