### ISSUE TITLE
Templates with two top level elements throw confusing error message

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#281]
If a component attempts to render a template with two top level elements, incremental dom will throw an error. However, the error message isn't totally clear on what component/template is causing the issue.

```soy
/**
 *
 */
{template .render}
  <div>Element 1</div>
  <div>Element 2</div>
{/template}
```

A template like the one above will throw an error like the following.

![image](https://user-images.githubusercontent.com/2466445/31744070-3b585602-b412-11e7-99cf-bc9171d31e04.png)

We should try to catch this incremental dom error and provide a more helpful message that includes the name of the component and how to fix the issue.

**Comment by robframpton** [comment]
Right now I have a branch with the following behavior. It captures any incremental dom errors and waits until the tree of components is done trying to render, then it composes an error that will associate the previously thrown errors with the name of the Component. For example,

If a single component had an issue.

```
There was a problem rendering TestComponent: Received a call to close "div" but "span" was open.
```

Or if multiple components had issues.

```
There were problems rendering multiple components.
TestChildComponent: Received a call to close "div" but "span" was open.
TestComponent: Received a call to close "span" but "div" was open.
```

When we compose this message we can also provide more helpful errors.

```
There was a problem rendering TestComponent: templates can only have one top level element, more than one element was found.
```

**Comment by eduardolundgren** [comment]
LGTM. Do you have the branch reference to look the implementation?

**Comment by robframpton** [comment]
Yep, I'll send a PR later this morning.

Edit: ran into some issues, might have uncovered an unrelated problem.
