### ISSUE TITLE
Multiple levels of Class inheritance when extending State causes static hint configuration issues

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#287]
Found when looking into test failures for metal-drag-drop: https://github.com/metal/metal-drag-drop/pull/8#issuecomment-340596886

When creating a new instance of class that extends from State, a flag is set on the constructor to indicate that has configured the state https://github.com/metal/metal.js/commit/2c50c73cdddc97c2a34c93abe2e06997bd6b6456#diff-0aee89f1c625f93fd4bfd8a5e3bbfb99R275.

However, when another class uses this class as a parent, that flag will already be set, and the configuration is not set up properly.

```javascript
class Parent extends State {
}

class Child extends Parent {
}

Child.STATE = {
  foo: {
    setter: function(val) {
      console.log('this is never called');
    }
  }
};

// Parent must be invoked first to reproduce
new Parent({});

const child = new Child({
  foo: 'foo'
});

child.foo !== 'foo';
```

**Comment by jbalsas** [comment]
This was merged to `develop` and scheduled for `2.14.0`
