### ISSUE TITLE
Provide events for all lifecycle methods on Component

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal.js#300]
Currently there are only some events dispatched during lifecycle methods (willAttach, attached, willDetach, detached and rendered). I think it would be useful (and more consistent) to provide events for all existing lifecycle methods, so components' users can listen for these changes.

I have made a PR (https://github.com/metal/metal.js/pull/299) for the disposed lifecycle method, but it would be interesting adding events for the rest of them (created, willReceiveState...).

---

*Example use case for the disposed event: I am storing a component inside a variable, and setting that variable to null when the component is disposed.*

**Comment by robframpton** [comment]
Fixed by #299
