### ISSUE TITLE
Lifecycle events and methods on metal-state

### ISSUE THREAD

**Issue by p2kmgcl** [metal/metal.js#303]
I have been working with metal-state and I have found a use case where adding some events and methods to metal-state would be useful. I know that lifecycle methods are thought to be used with components, but speaking about the "created" and the "disposed" events, maybe they fit in a State lifecycle too. Here is the use case:

I have created a component for using metal-drag-drop, and for that purpose. I create a DragDrop instance in the State constructor, and add listeners for this instance. When the State is not being used, I call it's disposed method in order to destroy the DragDrop instance too. This is part of the code for that:

```
class MyComponent extends State {
  constructor(config, ...args) {
    super(config, ...args)
    this.setState(config)

    this._dragDrop = new DragDrop();
    // ...
  }

  dispose(...args) {
     this._dragDrop.dispose();
     super.dispose(...args);
  }
}
```

And this would be the code with state-related lifecycle methods:

```
class MyComponent extends State {
  created() {
    this._dragDrop = new DragDrop();
    // ...
  }

  disposed() {
     this._dragDrop.dispose();
  }
}
```

In this case, using a Component does not make much sense, as I am not rendering any interface, just manipulating it, but I do have an initial state, and I do need a dispose process.

/cc @jbalsas

**Comment by robframpton** [comment]
Hey @p2kmgcl,

Is https://github.com/metal/metal.js/pull/299 for this issue? I wasn't sure because this issue is regarding the `State` class but the PR just adds the event to `Component`.

**Comment by p2kmgcl** [comment]
Hi @Robert-Frampton nope, they are similar, but no :smile: 

That PR was for issue https://github.com/metal/metal.js/issues/300, and thats only for metal-component, no state implied. This issue is just for knowing if having this part of the lifecycle on metal-state makes sense
