### ISSUE TITLE
[metal-events] Document process to emit events

### ISSUE THREAD

**Issue by jonathantneal** [metal/metal.js#308]
I’m unsure how to emit events when working with metal.

In my case, I would like to [emit events from metal-toggler](https://github.com/metal/metal-toggler/blob/master/src/Toggler.js) whenever the component expands or collapses. How might I do this? I could not find [emit documentation](https://metaljs.com/docs/guides/inline-events.html)

**Comment by pragmaticivan** [comment]
hey @jonathantneal thanks,

Just in case if that helps you while that gets documented : https://github.com/metal/metal-training

**Comment by robframpton** [comment]
Moving this over to metaljs.com/issues https://github.com/metal/metaljs.com/issues/86
