### ISSUE TITLE
[JSX] Unconfigured props will not be overwritten if a new undefined value is not passed in

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#374]
In the example below, the `GrandChild` component will not render its default prop of `'Default Two` after clicking the button. I believe this happens because metal.js calls [addUnconfiguredProps](https://github.com/metal/metal.js/blob/master/packages/metal-jsx/src/JSXDataManager.js#L18) but when that prop is not passed in anymore, it re-uses the old value because the prop is not explicitly passed in by its key anymore. 

For example, if both `foo` and `bar` are unconfigured props and we pass `{foo: 1, bar: 2}` followed by passing in `{foo: 2}`. The component will continue to use `bar: 2` because it doesn't know to remove that prop.

Check out this for a working example
```jsx
import Component from 'metal-jsx';

class GrandChild extends Component {
	render() {
		return (
			<div>
				{this.props.one}
				<br />
				{this.props.two}
			</div>
		);
	}
}

GrandChild.PROPS = {
	one: {
		value: 'Default One'
	},
	two: {
		value: 'Default Two'
	}
};

class ChildComponent extends Component {
	render() {
		return (
			<div>
				<GrandChild {...this.otherProps()} />
			</div>
		);
	}
}

class Parent extends Component {
	handleClick() {
		this.state.active = !this.state.active;
	}

	render() {
		const props = this.state.active
			? {one: 'foo'}
			: {one: 'bar', two: 'baz'};
		return (
			<div>
				<button onClick={this.handleClick.bind(this)}>click</button>

				<br />

				<ChildComponent {...props} />
			</div>
		);
	}
}

Parent.STATE = {
	active: {
		value: true
	}
};
```

cc @mthadley

**Comment by mthadley** [comment]
I think conceptually, this is also a bug, because a JSX component's `this.props` should always reflect what was passed to the component. In the above example, where `active` is true, there is no prop now called `two`, so `GrandChild` shouldn't see the value `'baz'`.

**Comment by travisrcory** [comment]
👎 Rob

**Comment by eduardolundgren** [comment]
cc @jbalsas

**Comment by jbalsas** [comment]
Hey guys, I'll take a look at this first thing next week!

This would be a breaking change... probably no-one is relying on this specific behaviour as it is, but I'll double check existing usages out there. I agree with the expected outcome.

**Comment by diegonvs** [comment]
@brunobasto @interaminense

**Comment by diegonvs** [comment]
There is an issue, React's props have the same behavior as @bryceosterhaus explained.

**Comment by diegonvs** [comment]
I'm taking this issue right now

**Comment by yuchi** [comment]
It’s Historically Accurate Note Time™!

>  I'll search some use cases using React's definition of props, that we have inspired to build metal props idea.

Actually the `State` concept in Metal has been inherited from [YUI `Attribute`](https://yuilibrary.com/yui/docs/attribute/) infrastructure and *then* retrofitted into props for JSX components.
