### ISSUE TITLE
[metal-useragent] User Agent is not being detected since v2.2.0

### ISSUE THREAD

**Issue by antonio-ortega** [metal/metal.js#382]
Hi,

User Agent is not being detected for any browser in version 2.2.0. It is working properly if I downgrade the package to 2.1.3.

As far as I know, it looks like the changes introduced [here](https://github.com/deprecate/metal-useragent/commit/8d7ac3adf05209da903b5693134fd873248b4164#diff-b4909c1f2e9370d3d9fe820aa508a871R163) are the root cause of this issue, since we were assigning window to UA.globals.window and now we're assigning window to UA.globals.

Thanks,

**Comment by diegonvs** [comment]
Hey @antonio-ortega, metal-useragent is now in https://github.com/metal/metal-plugins/. I have filed an issue for you at it.

**Comment by jbalsas** [comment]
Sorry, that was my fault, I forgot :(

Closing here. See also that @gcmznt sent a fix to https://github.com/metal/metal-plugins/pull/68
