### ISSUE TITLE
Describe why is this better than an existing solution

### ISSUE THREAD

**Issue by zenorocha** [metal/metal.js#81]
On [About](https://github.com/liferay/metal#about), we should be able to briefly describe **why** this framework is better than something out there. For example, why do we have a better API than Angular? Why is our solution faster than React's Virtual DOM? Basically why should people care about this?

**Comment by mairatma** [comment]
I think we've done this in the current metaljs.com site. Maybe it could be improved, but then we can create another issue, more recent, to metal/metaljs.com instead. Closing for now.
