### ISSUE TITLE
Make components render by default

### ISSUE THREAD

**Issue by natecavanaugh** [metal/metal.js#92]
I'm proposing we do away with requiring the render call manually, unless someone passes `render: false` as part of the config.

With YUI, in 90% of the cases, when we instantiated the component was also when we wanted to render it.
So my proposal would end up looking like:

```
let myCmp1 = new MyComponent({}); //renders component

let myCmp2 = new MyComponent({ render: false });
// do some work ...
myCmp.render();
```

What do you guys think?

**Comment by zenorocha** [comment]
Oh, I agree with that. Today, I forgot to do that.

**Comment by yuchi** [comment]
I'd be happy to loose that «oh yeah, I need to render it» moment.

**Comment by eduardolundgren** [comment]
SGTM. We can handle this improvement next week. Feel free to send pull request to it :)

**Comment by mairatma** [comment]
It took longer than a week, but we did this change now, creating a component now also renders it by default :)
